---

- name: Create LTM Profile FastL4
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_fastl4_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile FastL4
  assert:
    that:
      - result|changed

- name: Create LTM Profile FastL4 (idempotent)
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_fastl4_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile FastL4 (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Profile FastL4 description
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_fastl4_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile FastL4 description
  assert:
    that:
      - result|changed

- name: Change LTM Profile FastL4 description (idempotent)
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_fastl4_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile FastL4 description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Profile FastL4
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile FastL4
  assert:
    that:
      - result|changed

- name: Delete LTM Profile FastL4 (idempotent)
  f5bigip_ltm_profile_fastl4:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fastl4_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile FastL4 (idempotent)
  assert:
    that:
      - not result|changed