---

- name: Create LTM Monitor RealServer
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_real_server_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Monitor RealServer
  assert:
    that:
      - result|changed

- name: Create LTM Monitor RealServer (idempotent)
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_real_server_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Monitor RealServer (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Monitor RealServer description
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_real_server_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Monitor RealServer description
  assert:
    that:
      - result|changed

- name: Change LTM Monitor RealServer description (idempotent)
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_real_server_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Monitor RealServer description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Monitor RealServer
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Monitor RealServer
  assert:
    that:
      - result|changed

- name: Delete LTM Monitor RealServer (idempotent)
  f5bigip_ltm_monitor_real_server:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_real_server_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Monitor RealServer (idempotent)
  assert:
    that:
      - not result|changed