---

- name: Upload a Data Group List
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ dg_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Data Group List
  assert:
    that:
      - result|changed

- name: Upload a Key
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ key_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Key
  assert:
    that:
      - result|changed

- name: Upload a Cert
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ cert_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Cert
  assert:
    that:
      - result|changed

- name: Move Cert to madm folder
  f5bigip_util_unix_mv:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    file_name: "{{ cert_filename }}"
    source_path: "{{ madm_source_path }}"
    dest_path: "{{ madm_dest_path }}"
  delegate_to: localhost
  register: result

- name: Assert Move Cert to madm folder
  assert:
    that:
      - result|changed

- name: Download Cert
  f5bigip_shared_file_transfer_madm:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    file_name: "{{ cert_filename }}"
    download_path: "{{ cert_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Download Cert
  assert:
    that:
      - result|changed