---

app_name: "www.mycompany.com_http_80"
app_description: "my http app"
app_template: "/Common/f5.http"

app_tables:
  - name: basic__snatpool_members
  - name: net__snatpool_members
  - name: optimizations__hosts
  - name: pool__hosts
    columnNames:
    - name
    rows:
    - row:
      - www.mycompany.com
  - name: pool__members
    columnNames:
    - addr
    - port
    - connection_limit
    rows:
    - row:
      - 172.16.227.21
      - '80'
      - '0'
    - row:
      - 172.16.227.22
      - '80'
      - '0'
  - name: server_pools__servers

app_variables:
  - name: client__http_compression
    encrypted: 'no'
    value: "/#create_new#"
  - name: monitor__monitor
    encrypted: 'no'
    value: "/#create_new#"
  - name: monitor__response
    encrypted: 'no'
    value: 200 OK
  - name: monitor__uri
    encrypted: 'no'
    value: "/"
  - name: net__client_mode
    encrypted: 'no'
    value: wan
  - name: net__server_mode
    encrypted: 'no'
    value: lan
  - name: pool__addr
    encrypted: 'no'
    value: 172.16.227.201
  - name: pool__pool_to_use
    encrypted: 'no'
    value: "/#create_new#"
  - name: pool__port
    encrypted: 'no'
    value: '80'
  - name: ssl__mode
    encrypted: 'no'
    value: no_ssl
  - name: ssl_encryption_questions__advanced
    encrypted: 'no'
    value: 'no'
  - name: ssl_encryption_questions__help
    encrypted: 'no'
    value: hide