---

- name: Create NET DNS Resolver
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET DNS Resolver
  assert:
    that:
      - result|changed

- name: Create NET DNS Resolver (idempotent)
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET DNS Resolver (idempotent)
  assert:
    that:
      - not result|changed

- name: Change NET DNS Resolver use_ipv6
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    use_ipv6: "{{ dns_resolver_use_ipv6 }}"
  register: result

- name: Assert Change NET DNS Resolver use_ipv6
  assert:
      that:
        - result|changed

- name: Change NET DNS Resolver use_ipv6 (idempotent)
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    use_ipv6: "{{ dns_resolver_use_ipv6 }}"
  register: result

- name: Assert Change NET DNS Resolver use_ipv6 (idempotent)
  assert:
      that:
        - not result|changed

- name: Delete NET DNS Resolver
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET DNS Resolver
  assert:
    that:
      - result|changed

- name: Delete NET DNS Resolver (idempotent)
  f5bigip_net_dns_resolver:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ dns_resolver_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET DNS Resolver (idempotent)
  assert:
    that:
      - not result|changed