---

- name: Create LTM Profile Fast HTTP
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_fasthttp_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile Fast HTTP
  assert:
    that:
      - result|changed

- name: Create LTM Profile Fast HTTP (idempotent)
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_fasthttp_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile Fast HTTP (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Profile Fast HTTP description
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_fasthttp_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile Fast HTTP description
  assert:
    that:
      - result|changed

- name: Change LTM Profile Fast HTTP description (idempotent)
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_fasthttp_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile Fast HTTP description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Profile Fast HTTP
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile Fast HTTP
  assert:
    that:
      - result|changed

- name: Delete LTM Profile Fast HTTP (idempotent)
  f5bigip_ltm_profile_fasthttp:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_fasthttp_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile Fast HTTP (idempotent)
  assert:
    that:
      - not result|changed