---

- name: Create LTM Virtual Address
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    address: "{{ virtual_address_address }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Virtual Address
  assert:
    that:
      - result|changed

- name: Create LTM Virtual Address (idempotent)
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    address: "{{ virtual_address_address }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Virtual Address (idempotent)
  assert:
    that:
      - not result|changed

- name: Modify LTM Virtual Address icmp-echo
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    icmp_echo: "{{ virtual_address_icmp_echo }}"
  delegate_to: localhost
  register: result

- name: Assert Modify LTM Virtual Address icmp-echo
  assert:
    that:
      - result|changed

- name: Modify LTM Virtual Address icmp-echo (idempotent)
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    icmp_echo: "{{ virtual_address_icmp_echo }}"
  delegate_to: localhost
  register: result

- name: Assert Modify LTM Virtual Address icmp-echo (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Virtual Address
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Virtual Address
  assert:
    that:
      - result|changed

- name: Delete LTM Virtual Address (idempotent)
  f5bigip_ltm_virtual_address:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_address_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Virtual Address (idempotent)
  assert:
    that:
      - not result|changed