---

- name: Create LTM Profile Request Log
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_request_log_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile Request Log
  assert:
    that:
      - result|changed

- name: Create LTM Profile Request Log (idempotent)
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ profile_request_log_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Profile Request Log (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Profile Request Log description
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_request_log_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile Request Log description
  assert:
    that:
      - result|changed

- name: Change LTM Profile Request Log description (idempotent)
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ profile_request_log_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Profile Request Log description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Profile Request Log
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile Request Log
  assert:
    that:
      - result|changed

- name: Delete LTM Profile Request Log (idempotent)
  f5bigip_ltm_profile_request_log:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ profile_request_log_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Profile Request Log (idempotent)
  assert:
    that:
      - not result|changed