---

- name: Create LTM HTTPS Monitor
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_description }}"
    send: "{{ monitor_send_string }}"
    recv: "{{ monitor_recv_string }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM HTTPS Monitor
  assert:
    that:
      - result|changed

- name: Create LTM HTTPS Monitor (idempotent)
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_description }}"
    send: "{{ monitor_send_string }}"
    recv: "{{ monitor_recv_string }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM HTTPS Monitor (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM HTTPS Monitor description, interval and timeout
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_description }}"
    interval: "{{ monitor_interval }}"
    timeout: "{{ monitor_timeout }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM HTTPS Monitor description, interval and timeout
  assert:
    that:
      - result|changed

- name: Change LTM HTTPS Monitor description, interval and timeout (idempotent)
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_description }}"
    interval: "{{ monitor_interval }}"
    timeout: "{{ monitor_timeout }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM HTTPS Monitor description, interval and timeout (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM HTTPS Monitor
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM HTTPS Monitor
  assert:
    that:
      - result|changed

- name: Delete LTM HTTPS Monitor (idempotent)
  f5bigip_ltm_monitor_https:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ monitor_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM HTTPS Monitor (idempotent)
  assert:
    that:
      - not result|changed