---

- name: Create CM Traffic Group
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create CM Traffic Group
  assert:
    that:
      - result|changed

- name: Create CM Traffic Group (idempotent)
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create CM Traffic Group (idempotent)
  assert:
    that:
      - not result|changed

- name: Modify CM Traffic Group description
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    description: "{{ traffic_group_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Modify CM Traffic Group description
  assert:
    that:
      - result|changed

- name: Modify CM Traffic Group description (idempotent)
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    description: "{{ traffic_group_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Modify CM Traffic Group description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete CM Traffic Group
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete CM Traffic Group
  assert:
    that:
      - result|changed

- name: Delete CM Traffic Group (idempotent)
  f5bigip_cm_traffic_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ traffic_group_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete CM Traffic Group (idempotent)
  assert:
    that:
      - not result|changed