---

- name: Create LTM Monitor POP3
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_pop3_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Monitor POP3
  assert:
    that:
      - result|changed

- name: Create LTM Monitor POP3 (idempotent)
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ monitor_pop3_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Monitor POP3 (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Monitor POP3 description
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_pop3_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Monitor POP3 description
  assert:
    that:
      - result|changed

- name: Change LTM Monitor POP3 description (idempotent)
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ monitor_pop3_description }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Change LTM Monitor POP3 description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Monitor POP3
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Monitor POP3
  assert:
    that:
      - result|changed

- name: Delete LTM Monitor POP3 (idempotent)
  f5bigip_ltm_monitor_pop3:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ monitor_pop3_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Monitor POP3 (idempotent)
  assert:
    that:
      - not result|changed