---

- name: Change GTM Global Settings Metrics default probe limit
  f5bigip_gtm_global_settings_metrics:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    default_probe_limit: "{{ global_settings_metrics_default_probe_limit }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Settings Metrics default probe limit
  assert:
    that:
      - result|changed

- name: Change GTM Global Settings Metrics default probe limit (idempotent)
  f5bigip_gtm_global_settings_metrics:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    default_probe_limit: "{{ global_settings_metrics_default_probe_limit }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Settings Metrics default probe limit (idempotent)
  assert:
    that:
      - not result|changed
  
- name: Change GTM Global Settings Metrics default probe limit to default
  f5bigip_gtm_global_settings_metrics:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    default_probe_limit: "{{ global_settings_metrics_default_probe_limit_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Settings Metrics default probe limit to default
  assert:
    that:
      - result|changed

- name: Change GTM Global Settings Metrics default probe limit to default (idempotent)
  f5bigip_gtm_global_settings_metrics:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    default_probe_limit: "{{ global_settings_metrics_default_probe_limit_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Settings Metrics default probe limit to default (idempotent)
  assert:
    that:
      - not result|changed