---

node_name: my_node
node_description: My node
node_address: 10.10.10.101
node_monitor: /Common/icmp
node_connection_limit: 10
node_dynamic_ratio: 2
node_logging: enabled
node_rate_limit: 5
node_ratio: 2